# GitHub Pages config
theme: null
plugins: []
markdown: kramdown
kramdown:
  input: GFM
url: https://cryptotoolsguide.com
baseurl: 
include:
  - _includes/head.html
  - _includes/head-custom.html
  - _includes/header.html
  - _includes/footer.html
