# GitHub Pages config
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
url: https://bigfundz8.github.io
baseurl: /crypto-tools-guides
include:
  - _includes/head.html
  - _includes/head-custom.html
