name: Generate Daily Post
on:
  schedule:
    - cron: '0 9,13,17,21 * * *'   # 4x per dag (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Debug env
        run: |
          node -v
          git --version
          pwd
          ls -la
          ls -la scripts || true
          ls -la docs || true
          head -n 30 scripts/generate-post.js || true

      - name: Generate post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOTAL_POSTS: '4'
          AI_POSTS: '2'
        run: node scripts/generate-post.js

      - name: Commit and push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add docs/posts
          git commit -m "chore: add daily post" || echo "no changes"
          git push
